<?php


namespace Cxb\DingTalk\Driver;


use Cxb\DingTalk\AbstractDriver;
use Cxb\GuzzleHttp\ResponseClient;

/**
 * Class DepartmentDriver
 * @package Cxb\DingTalk\Driver
 */
class DepartmentDriver extends AbstractDriver
{
    protected function handleResponse(ResponseClient $response)
    {
        $body = parent::handleResponse($response); // TODO: Change the autogenerated stub
        return $body['result'] ?? null;
    }

    /**
     * 部门列表
     * @return array
     */
    public function list(): array
    {
        return $this->request( '/topapi/v2/department/listsub?access_token=' . $this->getAccessToken(),'GET');
    }
}